update the css classes
GitStartHQ/tech-screen-calcom pull request #1
Opened 2023-05-11 14:33 UTC by udayfakie

This PR fixes the issue with lowercase characters such as j,q,y being cut off at the bottom in the user profile section. The bottom section of these characters were previously hidden due to a styling issue.

Fixes https://github.com/calcom/cal.com/issues/8563

To fix this issue, I removed the block class and added the pb-1 class to the affected element in the code.

To test this fix, go to the user profile section and check if the bottom part of lowercase characters such as j,q,y are no longer hidden.

2023-05-16 17:04 UTC, niteshsingh1357 requested changes
@udayfakie Please add screenshots for before and after changes.
Left you a comment below

2023-05-16 17:04 UTC, niteshsingh1357 commented on packages/features/shell/Shell.tsx
> +                  <span className="text-default pb-1 truncate font-normal leading-none">
This does not solve the issue
<img width="210" alt="Screenshot 2023-05-16 at 9 00 21 PM" src="https://github.com/GitStartHQ/tech-screen-calcom/assets/31402501/ad349e96-3afd-48df-8032-9135f40ef968">

2023-05-16 19:11 UTC, Toledodev commented on packages/features/shell/Shell.tsx
> +                  <span className="text-default pb-1 truncate font-normal leading-none">
We still have the problem
![image](https://github.com/GitStartHQ/tech-screen-calcom/assets/87545086/879592e9-4bfb-44ee-91c8-35777c4132ca)

2023-05-17 14:31 UTC, udayfakie commented
@niteshsingh1357  here the before 
![before](https://github.com/GitStartHQ/tech-screen-calcom/assets/92738263/9680a0a7-0776-40f1-896e-26efa8120b5b)
and here the after
![after](https://github.com/GitStartHQ/tech-screen-calcom/assets/92738263/14746345-a48f-4354-99d9-d671ca17dfa3)

           <span className="text-default block truncate font-normal leading-none">
                  <span className="text-default pb-1 truncate font-normal leading-none">
it working perfectly in my local machine !

2023-05-17 14:48 UTC, udayfakie commented on packages/features/shell/Shell.tsx
> +                  <span className="text-default pb-1 truncate font-normal leading-none">
i tried removing the pb-1 and it works also perfect
i will continue investigating to identify the cause of the discrepancy and try to find a solution that works for everyone

2023-05-18 13:54 UTC, Toledodev commented
@udayfakie This is weird, on my machine only one it's working:
![image](https://github.com/GitStartHQ/tech-screen-calcom/assets/87545086/5f78a294-0174-4f44-bc81-f72e7b61b5a7)

2023-05-20 14:04 UTC, udayfakie commented on packages/features/shell/Shell.tsx
> +                  <span className="text-default pb-1 truncate font-normal leading-none">
I think the problem might be that I removed block from the className. I was having trouble creating another pull request to change this back. Can you check to see if it works if you put block back but keep the pb-1 that I added before?

2023-05-22 10:51 UTC, Toledodev requested changes

2023-05-22 10:51 UTC, Toledodev commented on packages/features/shell/Shell.tsx
> +                  <span className="text-default pb-1 truncate font-normal leading-none">
@udayfakie This is the behavior when we remove the "block" className:
![image](https://github.com/GitStartHQ/tech-screen-calcom/assets/87545086/08b73626-95f2-4113-8a1e-e4032338e0f6)

With the "block":
![image](https://github.com/GitStartHQ/tech-screen-calcom/assets/87545086/4c03d20d-6437-481f-abcf-b07f531b9919)

2023-05-22 10:51 UTC, Toledodev commented on packages/features/shell/Shell.tsx
>                  <span className="flex-grow truncate text-sm">
On our machine is not working because here on main branch we have the "leading-none" className, if we remove to let the same as your code it's working 👍 
![image](https://github.com/GitStartHQ/tech-screen-calcom/assets/87545086/4167baef-2821-487c-951b-44cab5204f43)

2023-05-22 10:51 UTC, Toledodev commented on packages/features/shell/Shell.tsx
> +                  <span className="text-emphasis mb-1 pb-1 block truncate font-medium leading-none">
We can't remove this "block", check [here ](https://www.loom.com/share/1f9212de47f14498b178eae2ca187b9a)please 😄

2023-05-22 19:00 UTC, udayfakie commented on packages/features/shell/Shell.tsx
> +                  <span className="text-emphasis mb-1 pb-1 block truncate font-medium leading-none">
I tried to push a change adding back block but had some issues pushing to my fork (is it still active?), other than that I hope this is resolved.

2023-06-23 00:10 UTC, closed without merging